server:
    port: 8773

spring:
    application:
        name: servicethree
    zipkin:
        base-url: http://www.curvelife.cn:9411

    sleuth:
        sampler:
            probability: 1
